languageCode = "en-us"
title = "Evan Spangler Consulting"
baseURL = "https://evanspangler.github.io"
theme = "hugo-theme-massively"
googleanalytics = "G-D5M6GG9J6L"
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "IT infrastructure, cloud solutions, custom systems, and security. Over a decade of experience across federal, startup, and enterprise environments."
  # favicon = "favicon.ico"
  # dateFormat = "2.1.2006"
  # backgroundPath = "images/bg.jpg"

[params.posts]
    folderName = "post"
    pageSize = "100"
    featuredPost = "false"

[languages]
[languages.en]
  languageName = "English"
