languageCode = "en-us"
title = "Evan Spangler Consulting - Technology Solutions"
baseURL = "https://evanspangler.github.io"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "IT infrastructure, cloud solutions, custom systems, and security. Nearly a decade of experience across federal, startup, and enterprise environments."
  # favicon = "favicon.ico"
  # dateFormat = "2.1.2006"
  # backgroundPath = "images/bg.jpg"

[params.posts]
    folderName = "post"
    pageSize = "3"
    featuredPost = "true"

[languages]
[languages.en]
  languageName = "English"
